DATA:
  data_name: s3dis
  data_root: dataset/s3dis
  train_list: dataset/s3dis/list/train12346.txt
  train_full_folder: dataset/s3dis/trainval_fullarea
  val_list: dataset/s3dis/list/val5.txt
  test_area: 5
  classes: 13
  fea_dim: 6  # point feature dimension
  block_size: 1.0
  stride_rate: 0.5
  sample_rate: 1.0
  num_point: 4096  # point number [default: 4096]

TRAIN:
  arch: pointweb_seg
  use_xyz: True
  sync_bn: True  # adopt sync_bn or not
  ignore_label: 255
  train_gpu: [0, 1, 2, 3]
  train_workers: 8  # data loader workers
  train_batch_size: 16  # batch size for training
  train_batch_size_val: 8  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.05
  epochs: 100
  start_epoch: 0
  step_epoch: 30
  multiplier: 0.1
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed:
  print_freq: 10
  save_freq: 1
  save_path: exp/s3dis/pointweb/model
  weight:  # path to initial weight (default: none)
  resume:  # path to latest checkpoint (default: none)
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend

TEST:
  test_list: dataset/s3dis/list/val5.txt
  test_list_full: dataset/s3dis/list/val5_full.txt
  split: val  # split in [train, val and test]
  test_gpu: [0]
  test_workers: 4
  test_batch_size: 8
  model_path: exp/s3dis/pointweb/model/train_epoch_100.pth
  save_folder: exp/s3dis/pointweb/result/epoch_100/val5_0.5  # results save folder
  names_path: data/s3dis/s3dis_names.txt
