DATA:
  data_name: scannet
  data_root: dataset/scannet
  classes: 21
  # fea_dim: 3  # point feature dimension
  block_size: 1.5
  stride_rate: 0.5
  sample_rate: 1.0
  num_point: 8192  # point number [default: 8192]
  fea_dim: 6
  voxel_size: 0.04
  voxel_max: 80000
  loop: 15


TRAIN:
  arch: pointtransformer_seg_repro
  use_xyz: True
  sync_bn: False  # adopt sync_bn or not
  ignore_label: 255
  train_gpu: [4,5,6,7]
  workers: 1   # data loader workers
  batch_size: 16  # batch size for training
  batch_size_val: 4   # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.001
  epochs: 50
  start_epoch: 0
  step_epoch: 30
  multiplier: 0.1
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed: 7777
  print_freq: 10
  save_freq: 1
  save_path: exp/scannet/baseline
  weight:  # path to initial weight (default: none)
  resume:  # path to latest checkpoint (default: none)
  evaluate: False  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 1 # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  # correlation_loss: True
  # correlation_loss_scale: 10.0
Distributed:
  dist_url: tcp://localhost:8888
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0

TEST:
  test_list: dataset/s3dis/list/val5.txt
  test_list_full: dataset/s3dis/list/val5_full.txt
  split: val  # split in [train, val and test]
  test_gpu: [0]
  test_workers: 4
  batch_size_test: 4
  model_path: None
  save_folder:
  names_path: data/s3dis/s3dis_names.txt
